### ISSUE TITLE
ESP8266 vs ESP-01

### ISSUE THREAD

**Issue by Natetronn** [dx4m/Modern-Xbox-EEPROM-Dumper#2]
Hi,

You mention ESP8266 and ESP-01 and I'm a little bit confused between the two. Would you mind explaining the difference as it relates to your utility? 

https://www.amazon.com/HiLetgo-Internet-Development-Wireless-Micropython/dp/B010O1G1ES?th=1

https://www.amazon.com/MakerFocus-Wireless-Transceiver-DC3-0-3-6V-Compatible/dp/B01EA3UJJ4

https://oshpark.com/shared_projects/FJLqjN4W

Thanks!

**Comment by lowtolerance** [comment]
ESP-01 modules are standalone ESP8266 boards — you have to wire them to up a programmer to flash them, then wire them up to the Xbox to use them. What’s more common is to buy an ESP8266-based development boards like the Wemos D1 Mini that has a built in programmer and microUSB port, so you can easily flash it, and you can then power the device directly off the Xbox’s USB port.

**Comment by Natetronn** [comment]
Thanks @lowtolerance, that's kind of what I was thinking but, wanted to verify to solidify my thoughts on the matter.

Is the Wemos D1 Mini similar (at least in theory) to the first link I posted above? The ESP8266 CP2102 NodeMCU ESP-12E?

**Comment by lowtolerance** [comment]
Yes, the D1 Mini is actually based on the NodeMCU v3 design. It should work with this code without any modifications (although I haven’t verified it myself).

**Comment by dx4m** [comment]
> Yes, the D1 Mini is actually based on the NodeMCU v3 design. It should work with this code without any modifications (although I haven’t verified it myself).

I tested the ESP-01 black modules and the D1 Mini.

For the wiring on the ESP-01 you could order the adapter pcb from oshpark for easy attach, or with some wires. Keep in mind to connect the CHIP_EN pin to VCC(3.3V) when you use the wiring method, otherwise it wouldn't run. You also need a way to program the chip.

For the D1 Mini or the NodeMCU models you're ready to rock because it has the "programmer" on board. When you flash the precompiled binary to these boards, connect GND, pin D4 to SDA and D3 to SCL on your Xbox.

When you compile it yourself you can change the pin configuration as you want.
For example when you comment the line "#define ESP01 1" then it uses D1 as SCL and D2 as SDA.

Hope this helps.

**Comment by Natetronn** [comment]
That does help, thanks to you both!

To start, I'll probably go with a NodeMCU or D1 Mini, as I don't have a programmer and I'm already familiar with Arduino Micro Pro and their setup.
