### ISSUE TITLE
ESP32 support

### ISSUE THREAD

**Issue by lowtolerance** [dx4m/Modern-Xbox-EEPROM-Dumper#3]
Awesome update! I’ve actually been working on something similar to XWifi for the ESP32 and ran into trouble — they consume a lot more power at peak than the esp8266, and the Xbox’s standby rail is very low power. WiFi with the esp32 doesn’t work on most Xboxes I’ve tried it on without additional circuitry, but it *does* seem to work on motherboards with a working clock cap, and it works elsewhere with the addition of a working supercapacitor somewhere in circuit with the 3.3v standby rail.

**Comment by dx4m** [comment]
Hi, nice to hear!

I have not tested the ESP32 with XWiFi. The power consumption is pretty high even for the ESP8266.
My power supply(Delta) draws on the standby line usually 20mA and around 50mA when its on. With the ESP8266 installed it consumes about 90mA to 100mA in standby and 120mA when the console is on. And even 140mA when the standby light is configured at 100% with both red and green leds. The Delta power supply is rated about 75mA available for power draw. So there might be some wear on it. The ESP8266 power consumption is about 70mA to 250mA, so the consoles power supply could fail overtime. 

I've not tested the other power supplies because the only consoles i have, all of them has a Delta power supply inside and all of them has a v1.4 motherboard in it with the clock cap replaced. I would rather use a separate power supply only for the ESP instead of a super cap. Something you could mount safely in the console without shorting and with about 3.3V 600mA power output.

I would like to test other supplies but here in my local area(Austria), nobody sales OG Xboxes, and when, these are modded and preloaded with games and sold to rather high prices (200€+).

Because all of this, the ESP32 with XWiFi isn't supported at the moment.

greetings

**Comment by lowtolerance** [comment]
Working with the OG Xbox’s standby voltage is surprisingly challenging. The modem transmissions from the esp32 and esp8266 create very high peak current demands that are hard to satisfy. I had never had success with it with an esp8266, but then, I’ve never tried it on an 1.4 Xbox.

**Comment by dx4m** [comment]
Hi, I've did some research in the past days. The only thing you "could" do, is to replace the 3.3V LDO on the PSU with a bigger one. Something about a 600mA 3.3V LDO with filter caps. But i don't know how much power the 5V line would deliver to the LDO. Might do some more research.

**Comment by lowtolerance** [comment]
That’s a really interesting idea that had not occurred to me at all. I happen to have some blank SOT-23-6 breakout boards, I might get a sampling of 3.3V LDOs and give this a go. I’ll keep you posted if I get anywhere with it 👍

**Comment by dx4m** [comment]
Any news about it?
I didn't had the time since then to test a new 3.3V LDO.

**Comment by lowtolerance** [comment]
I’ve been busy with other things, too, but I have not forgotten about this LDO idea of yours. I am still interested in finding a suitable replacement, and I still don’t see any reason why it shouldn’t work.

**Comment by lowtolerance** [comment]
Rather than replace the LDO on the PSU, I decided to wire up one of these $1 AC-to-DC converters: 

https://a.aliexpress.com/_mPqLpqi

I just soldered its neutral and load pins to the mains power leads and have it output its own 3.3V power in addition to the standby rail. 

![DD72F17A-92CA-4637-BF9F-1977B09BBE28](https://user-images.githubusercontent.com/236495/135156913-0c3fa7d8-e20c-4eb3-b8e9-3da97bde11c7.jpeg)
![88B32B10-A502-4192-8E79-8A90788BC479](https://user-images.githubusercontent.com/236495/135156918-23e63f57-697e-42cd-8410-87e4a2e4a839.jpeg)
![F809C943-E3E3-4648-8BF2-051C691DD284](https://user-images.githubusercontent.com/236495/135156920-3203b463-d2d6-42a3-8606-dfe4cda50b4a.jpeg)
